### PR TITLE
update kustomization and others to satisfy avr and drclusterpeers cha…

### PR DESCRIPTION
**Pull request by BenamarMk**
…nges

### CODE REVIEW

**Comment by BenamarMk** [comment]
Don't merge until https://github.com/RamenDR/ramen/pull/51 is merged
PR#51 is needed for this change to have effect.

**Review by vdeenadh — APPROVED** [review]
LGTM

**Comment by ShyamsundarR** [comment]
PR #4 moves to the latest scheme, this can be closed as a result, thanks!

**Comment by ShyamsundarR** [comment]
Addressed by latest changes, closing this PR.

**Pull request closed without merging**
