### PR TITLE
Add demo VMs

### PR DESCRIPTION
**Pull request by nirs**
Add demo VMs using more realistic VM configurations.

- Fedora 40 server with 2 cpus, 2g RAM, and 6g disk
- Windows server 2022 with 4 cpus, 8g RAM, and 40g disk
- Match VM size to kubevirt common templates
- Replace commonLabels with labels

The demo VMs include a demo web application showing how data is preserved in failover and relocate and the downtime during failover and relocate.

Example page after relocate:

Screenshot from 2024-08-08 21-06-08

Tested on drenv and OpenShift.

### CODE REVIEW

**Comment by ShyamsundarR** [comment]
I do not see how this adds to samples, maybe we need to create a demo project and add demos in there?

What I mean is, it is another VM sample so from an overall sample perspective VMs are already covered by the existing VM sample. Adding another does not aid the samples, in which we intend to keep samples of various workload types and how to prepare them for required DR protection.

This new VM example can form a good demo source though, and hence suggest that we can move this to a demo repository under the org. and not retain it in samples. Thoughts?

**Comment by nirs** [comment]
> This new VM example can form a good demo source though, and hence suggest that we can move this to a demo repository under the org. and not retain it in samples. Thoughts?

This was also my idea, but @raghavendra-talur suggested to add to the samples. A demos project under RamenDR org sounds good!

**Comment by nirs** [comment]
Moving to https://github.com/RamenDR/demos

**Comment by nirs** [comment]
Moved to https://github.com/RamenDR/demos

**Pull request closed without merging**
